### PR TITLE
Review submitted changes

### PR DESCRIPTION
**Pull request by SteveBarnett**
@arthurattwell This is all getting a bit meta. Here's a Pull Request for you to review how we are presenting reviewing Pull Requests without calling them Pull Requests when people are making Electric Books.

This is part of https://github.com/electricbookworks/electric-book-gui/issues/37.

### CODE REVIEW

**Comment by arthurattwell** [comment]
@SteveBarnett Cool. Should the submission titles be smaller, in case they get very long? Your mobile-first default has them at 1.375em, which looks better to me on large screens, too?

**Comment by SteveBarnett** [comment]
@arthurattwell Re 1.375em: cool with me, done in https://github.com/electricbookworks/electric-book-gui/pull/58/commits/47fdc54b76804f4441a59f1dbdbdbd73af39e017 

Happy with the rest? :)

**Comment by arthurattwell** [comment]
@SteveBarnett Testing this now, something seems to have broken the CSS in `master`, which was then merged in here. I get a 404 from `/css/main.css`.

**Comment by arthurattwell** [comment]
@SteveBarnett Just saw https://github.com/electricbookworks/electric-book-gui/commit/166f2979c3afcc03850e86ba9684732b52a0e0a2 -- will try that first.

**Comment by arthurattwell** [comment]
@SteveBarnett Two things, which may be the result of me being too low on the FED/`gulp` learning curve:

1. REVENGE is now baked in. Do we really need it in our `main.css` when we can use the bookmarklet to the same effect? Having it baked in makes testing for appearance hard.
2. I don't see the smaller `h3` in `review-pull-requests`, but headings on the dashboard are now too small. Did 47fdc54 apply the change to the wrong place, or am I missing something?

**Comment by SteveBarnett** [comment]
1. I am strongly of the opinion **yes**. We want to make "good behaviour" as automatic as possible, and where we can't do that we want to make checking for good behaviour as automatic as possible. Having it baked in means the check happens automatically, and we don't have to remember to use the bookmarklet. (We may pull revenge out again later once we have our "real" tests up and running, which I want to focus on next sprint). Can you clarify what you mean by "makes testing for appearance hard", please? Thank you! :)
2. Whoops, that was my mistake. Sorry! I put the styles in the wrong place 😬 . Fixed up in https://github.com/electricbookworks/electric-book-gui/pull/58/commits/33cabd28b10283fcddfa0c5c435e2f0a4010f8e3 .

**Comment by arthurattwell** [comment]
@SteveBarnett :+1: 

1. I like your strong opinions :) While the style-guide looks fine, the 'live' (not style-guide) [dashboard](http://localhost:16101/) is vengeful indeed:

    image

   Will that be fixed when you apply the style guide to the other pages? I'm just worried that while we're wiring up the rest, the issues that revenge is showing up might take a long time to solve. So I'd love an easy way to turn it off manually during demos in particular. I'm happy to go ahead with this branch though. A discussion about how to manage revenge.css shouldn't hold it up.

2. Thanks!

**Comment by SteveBarnett** [comment]
@arthurattwell I have un-venged the dashboard. The flags were mostly due to placeholder `a href="#"`s. :)

**Pull request merged**
