### PR TITLE
Leaner repo listing

### PR DESCRIPTION
**Pull request by SteveBarnett**
@arthurattwell Could you cast your peepers at this, please? I've been looking at:

- how to differentiate between the ownership and fork-age of repos. I've added lots of `Note:`s to highlight the difference between each example row. I've gone with "Name's version of" to indicate forkage and "by" to indicate ownership. It feels the most "editorial"? What do you think?
- when to show buttons. "Make my own version" only appears on things you can fork, but is `disabled` if you already have a fork.
- a decent responsive layout. The actions buttons stay under on small screens, and jump to the top left on larger screens. The repo name and description are kept to `38em` for easy readage.

### CODE REVIEW

**Comment by SteveBarnett** [comment]
I've added a first draft of the jargon-buster / dictionary. I'm think we might overload "changes" and use it for:

- working tree stuff before a commit and
- commits (and file changes) before a PR.

I'll figure that out once I'm working on those bits.

**Comment by SteveBarnett** [comment]
And now I'm pushed a first draft of what happens once you hit "Make a new version": you get prompted to say what you mean: edits, translation, or adaptation.

**Comment by arthurattwell** [comment]
@SteveBarnett Thanks! I've had a good look and have some thoughts/suggestions, also based on speaking to some users about terminology (Karen and Dione).

1. In CSS, I think we should use `.repo` not `.electric-book` -- i.e. our code should refer to the git concepts they refer to. I'm thinking that git concepts more likely reflect what the API is doing (easier for devs to follow), and are less likely to change than our front-end terms, which may well change.
2. We've been talking about 'book-name', but actually each repo is actually a potential series of books. So our terminology should probably reflect that, while taking into account that most repos we've created to date have included only one book. So, perhaps 'Edit book' could just be 'Edit'?
3. Could it be that we don't need separate buttons for 'Edit book' and 'Make a new version'? Unless I'm missing something, one of those is always disabled, and the user's *intent* is always to edit. So, if the user doesn't already have write access (it's not their repo or own fork), then the button goes to what happens when you 'make a new version', which is to give the user the 'edit/translate/adapt' choice, and in doing so to signal that we're making them a copy of the repo. This came up in conversation with Karen and Dione, for whom the difference between 'Edit' and 'Make a new version' was not clear, because the outcome of either is essentially the same. (I realise using one button instead of two could complicate things for you and @craigmj!)
4. For mapping git-to-editorial terminology, below are some further ideas. Karen and Dione, who are non-technical, argue that we *should* use some basic, key git terminology as-is. In particular, they like the terms 'repo' and 'commit', because those are close enough to their regular meanings to be useful and accurate. Other terms like fork, working tree, pull request and merge they felt were more advanced and could be translated into non-technical equivalents. I've added a few terms here, too.

    | Technical term              | Non-technical term               |
    |:----------------------------|:---------------------------------|
    | Repo                        | Repo                             |
    | Branch*                     | Version                          |
    | Stuff in the working tree   | Work-in-progress                 |
    | Save working tree           | Save work-in-progress            |
    | Commit (verb)               | Commit changes                   |
    | Commit (noun)               | Committed changes                |
    | Repo at a given commit      | Snapshot                         |
    | My commits                  | My committed changes             |
    | Fork                        | Copy                             |
    | Fork a repo                 | Edit a copy                      |
    | My fork                     | My copy                          |
    | User's repo                 | User's repo                      |
    | Pull Request(s)             | Submission(s) for review         |
    | Make Pull Request           | Submit changes for review        |
    | Upstream master             | The original                     |
    | Update from upstream master | Get latest updates from original |


    \* We don't need branches now, but in conversation with Karen and Dione, they like the idea of eventually supporting them, perhaps in an 'advanced mode', and that the term 'version' seems closest conceptually to a branch. So we'd be reserving the term 'version' to use for branches later on. Also, the term 'commit to version' is then consistent with the git concept of committing *to a branch*. This means 'version' cannot be used to refer to a repo or branch at a point in time (i.e. repo state at a given commit). For that, I've proposed 'snapshot', though this might not be best and we might not need it.

A final thought: I'm a big fan of buttons with tooltips that give me more info about what the button will do. How does that gel with accessibility needs? (When there are shortcut keys, I also love tooltips that tell me the shortcut keys, but that's for later :-) )

**Comment by SteveBarnett** [comment]
@arthurattwell Ooh, this is good stuff! 🙌 

1. Good thinking, solid reasoning, I concur. Fixed in https://github.com/electricbookworks/electric-book-gui/pull/52/commits/04909a3c552042528efdb9ef7a0a7dce4b6b21c1.
2. Good point, and something I keep forgetting 😊. Fixed in https://github.com/electricbookworks/electric-book-gui/pull/52/commits/0e302007ace4532ff46b07c0555776e430962934 . (Aside: I'd like to chat in person (and maybe note here) why we want to keep allowing for multiple books in one repo. I'm wondering if the "keep in the same place" angle might add more complexity than it solves. My vague direction of thinking is that one book per repo might also help with https://github.com/electricbookworks/electric-book/issues/106.)
3. There is a case where (both buttons would be there and) you could edit or make a new version: a book in your org that you can edit, that you don't have a fork of. You may want to take a personal fork of that. I've added that example in https://github.com/electricbookworks/electric-book-gui/pull/52/commits/b7c6d0a44ddbb144ed31e9b43d560f08398acbb2 . The user's intent is always to edit, but I think it needs to be clear if they're editing **this one** (e.g. the org's one), or making a **new version to edit** (yours, probably for submitting changes). I think we need better words for "Make a new version". Thankfully, you have them in 4 in this list :D. (Re one button (if we did that): I think we'd still have two buttons, we'd just have an `if` to show the appropriate one?)
4. This is gold! \o/  I've updated the README and style guide with these wordings in https://github.com/electricbookworks/electric-book-gui/pull/52/commits/dd5933ba947dc940a5daa5c8ac039492ed78689f.

Re tooltips: I'm sort of not a fan of tooltips if they're hidden behind hovers. General UX-y principles says that: **Link / button text that explains the action + visible helper text** (if it's necessary) is better (if possible). Can you give me an example of one or two that are unclear, and we can have a look at better action text + helper text? :). 
For keyboard shortcuts: I like the Trello style version. Hit `?` to see the keyboard shortcuts :).

---

Are you happy with the additional changes, and to take any extra bits into a new PR?

**Comment by arthurattwell** [comment]
@SteveBarnett Great :+1: to go with these changes. Then to your comments:

1. Super.
2. Multiple books in a repo is a must-have. I use it all the time (Book Dash, Bettercare, Worldreader, Pan Macmillan series, etc.). Often, sets of books are closely related, sometimes so much as to form one body of work. The ability to edit one config and styles for these and have them all in one website is critically important.
3. Duh, of course, thanks. I like the idea of an `if` to show only one button.
4. Thanks!
5. Re tooltips: let's leave that for a separate chat another day. Not important now. I was wondering whether we want to add what each button's doing in Git terms, to help teams (or even ourselves) understand and remember how we've mapped git to editorial. Helper text could do this, too. But let's park that idea, it would just be a distraction right now.

**Pull request merged**
